name: CI Build

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup .NET Core 3.1.102
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
          
      - name: Build Project
        run: dotnet build --configuration Release
      
      - name: Run Unit Tests
        run: dotnet test UnitTests/GitHubActions.Azure.Tests/GitHubActions.Azure.Tests.csproj
